"""add attempts to password reset token

Revision ID: 7b71c7086eaa
Revises: 567e2b7bfb30
Create Date: 2026-09-15 00:17:50.526409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b71c7086eaa'
down_revision: Union[str, None] = '567e2b7bfb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'attempts')
    # ### end Alembic commands ###
